### ISSUE TITLE
REST API works, but browser shows nothing

### ISSUE THREAD

**Issue by glinders** [kwk/docker-registry-frontend#110]
## Expected behavior

When I start the browser I expect to see the images in my registry, instead I see nothing. (See `lynx` output below.)

This is my YML file for the frontend for docker-compose:

```
frontend: 
  image: konradkleine/docker-registry-frontend:v2-develop
  ports: 
    - 127.0.0.1:8000:80 
  environment: 
    ENV_DOCKER_REGISTRY_HOST: docker.au.ivc
    ENV_DOCKER_REGISTRY_PORT: 80
```

The registry is served by `nginx` on port 80 on site http://docker.au.ivc.

This is my YML file for the registry and nginx for docker-compose:

```
nginx:
  image: "nginx:1.9"
  ports:
    - 80:80
  links:
    - registry:registry
  volumes:
    - ./nginx/:/etc/nginx/conf.d:ro
    - /var/www:/var/www:ro

registry:
  image: registry:2.3.1
  ports:
    - 127.0.0.1:5000:5000
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    REGISTRY_STORAGE_DELETE_ENABLED: 'true'
  volumes:
    - ./data:/data
```
- [x] _Please describe what you tried to do and what you expect the software to act like._
## Actual behavior

When I start the frontend using docker-compose I get:

```
Starting dockerregistry_frontend_1
Attaching to dockerregistry_frontend_1
frontend_1 | Module auth_kerb already disabled
frontend_1 | Module ssl already disabled
frontend_1 | Module rewrite already enabled
frontend_1 | Stopping web server: apache2.
frontend_1 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
```

I can access my registry directly:

```
$ curl 127.0.0.1:5000/v2/_catalog
{"repositories":["hello-world"]}
```

This proves that the registry is up on port 5000.

Now the frontend. I can access my registry directly via the REST API feature of the frontend:

```
$ curl 127.0.0.1:8000/v2/_catalog
{"repositories":["hello-world"]}
```

This means that the frontend is working and connects to the correct host and port.

But if I try to connect to the browser, I get:

```
$ curl 127.0.0.1:8000/
<!doctype html> <html class="no-js" ng-app="docker-registry-frontend" ng-controller="MainController as main"> <head> <base href="/"> <meta charset="utf-8"> <title ng-bind-template="Docker registry {{main.$location.path()}}">Docker registry</title> <meta name="description" content=""> <meta name="viewport" content="width=device-width"><!-- Place favicon.ico and apple-touch-icon.png in the root directory --> <link rel="stylesheet" href="styles/vendor.8f78f383.css"> <link rel="stylesheet" href="styles/main.b760445a.css"> </head> <body><!--[if lt IE 7]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]--><!-- Add your site or application content here --> <div class="container"> <div class="masthead"> <h3 class="text-muted">Docker Registry Frontend</h3> </div> <main ng-view></main> <footer> <p> <a href="https://github.com/kwk/docker-registry-frontend/issues/new"><span class="glyphicon glyphicon-fire"></span> <small>Report a bug</small></a> <a href="https://github.com/kwk/docker-registry-frontend/fork"><span class="glyphicon glyphicon-random"></span> <small> Fork me on GitHub</small></a> <a href="about"><span class="glyphicon glyphicon-question-sign"></span> <small>About</small></a> <a href="https://github.com/kwk/docker-registry-frontend/commit/{{appVersion.git.sha1}}"><span class="glyphicon glyphicon-barcode"></span> <small>This is git revision: <span ng-bind-template="{{appVersion.git.sha1 | limitTo: 7}}">-</span></small></a> </p> </footer> </div><!--[if lt IE 9]>
    <script src="scripts/oldieshim.aa1b403c.js"></script>
    <![endif]--> <script src="scripts/vendor.450eaef8.js"></script> <script src="scripts/scripts.c5d59356.js"></script>
```

The logs for the frontend shows the following fro the previous two commands:

```
frontend_1 | 172.17.0.1 - - [16/Mar/2016:23:32:42 +0000] "GET /v2/_catalog HTTP/1.1" 200 258 "-" "curl/7.35.0"
frontend_1 | 172.17.0.1 - - [16/Mar/2016:23:32:52 +0000] "GET / HTTP/1.1" 200 2059 "-" "curl/7.35.0"
```

This results in an empty screen with no registry. The same again, but now using `lynx 127.0.0.1:8000` :

```
Docker Registry Frontend

   Report a bug Fork me on GitHub About This is git revision: -
```

This shows an empty page with no Docker repositories.
## Specifications

```
$ docker --version
Docker version 1.10.2, build c3959b1
$ docker-compose --version
docker-compose version 1.6.2, build 4d72027
$ docker images | grep "docker-registry-frontend"
konradkleine/docker-registry-frontend   v2                  2266968ec9f7        21 hours ago        227.2 MB
konradkleine/docker-registry-frontend   v2-develop          7e2b165bc38c        21 hours ago        225.7 MB
```

I've tried with both your `v2` version and `v2-develop` version; they both respond the same.
