### ISSUE TITLE
ENV_REGISTRY_PROXY_PORT should be optional and not default to 5000.

### ISSUE THREAD

**Issue by mohammedzee1000** [kwk/docker-registry-frontend#172]
## Expected behaviour

- [x] *If ENV_REGISTRY_PROXY_PORT is not provided, it should not appear in the UI.*

## Actual behaviour

- [x] *The port defaults to 5000*

## Steps to reproduce the problem

- [x] *Run the standard docker container, while providing ENV_REGISTRY_PROXY_FQDN, and not provide ENV_REGISTRY_PROXY_PORT*

## Specifications

 - [x] 1.12
 - [x] Fedora 25
 - [x] v2

**Comment by mohammedzee1000** [comment]
ping @kwk

**Comment by kwk** [comment]
@mohammedzee1000 I was on vacation. Is the problem solved?

**Comment by SteveEdson** [comment]
This is still happening, running behind Traefik:

```yaml
registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    restart: always
    environment:
      ENV_DOCKER_REGISTRY_HOST: 'registry'
      ENV_DOCKER_REGISTRY_PORT: 5000
      ENV_REGISTRY_PROXY_FQDN: 'my.domain.com'
```

Shows in the UI as

```bash
docker pull my.domain.com:5000/image-name:latest
```

Not a massive issue as it can simply be fixed with:

```
ENV_REGISTRY_PROXY_PORT: 443
```
