### ISSUE TITLE
no delete button on WEB UI, button disabled

### ISSUE THREAD

**Issue by sunyao5588** [kwk/docker-registry-frontend#203]
***Before you open an issue, you should search for similar issues.
Especially for issues that deal with starting the docker-registry-frontend we have seen a tremendous amount
of issues and most of the time a reference to the [example-setup](https://github.com/kwk/docker-registry-frontend/tree/v2/example-setup)
folder was enough for the issue reporter to solve the issue on her own.***

Please, make sure to provide all the information asked for below and then delete everything above **Expected behavior** including this line.

## Expected behavior
delete button should be seen on Web UI, but not.
- [x] *Please describe what you tried to do and what you expect the software to act like.*

## Actual behavior
The delete button is disabled.
- [x] *Please describe what happened instead of the expected behavior.*

## Steps to reproduce the problem

- [x] *Please describe how a developer can reproduce the issue that you faced.
Make sure you include information how you configured or started the registry and the frontend.*

## Specifications

 - [x] Which version of docker (`docker version`) are you running? 18.03.1-ce
 - [x] Which operating system do you use? CentOS 7.5
 - [x] Which version of the docker-registry-frontend are you running? konradkleine/docker-registry-frontend:v2
  * If you have the frontend running already you can find the version at the very bottom on every page.
  * Otherwise you can provide the output of `docker images | grep "docker-registry-frontend"`.

**Comment by ryanrca** [comment]
I have this issue too.  When I refresh each screen, I see the red delete button flash, then quickly disappear.  

Inspecting the application in dev tools on chrome, I found this code commented out:
```
<!--<div ng-hide="appMode.browseOnly" class="pull-right">
    <a class="btn btn-danger" href="tag/{{repositoryUser}}/{{repositoryName}}/{{tagName}}/{{imageId}}/delete" alt="Delete tag">
      <span class="glyphicon glyphicon-trash"></span> Delete Tag
    </a>
  </div>-->
```

I suspect there is some javascript commenting this out or something?  Why?
"browse only mode"?

**Comment by ryanrca** [comment]
I tried running with: ```
-e ENV_MODE_BROWSE_ONLY=false
```
and it had no effect.  The delete button was disabled/gone.

**Comment by presidenten** [comment]
Seems like he didnt finish the other mode

![image](https://user-images.githubusercontent.com/3883897/54370370-c9128f00-4677-11e9-84b3-587a5e5b7c64.png)

Check out the override on line 41
https://github.com/kwk/docker-registry-frontend/blob/v2/start-apache.sh

Edit:
Semi out of topic, but I switched to this UI: https://github.com/Joxit/docker-registry-ui

I run it like this and I can finally delete images. Yey. :-)
(Ps. I run it with a proxy running in another service, so remove the proxy network and open ports as you see fit to make it work for you)

```
version: '3.7'

services:
  registry:
    image: registry:2.7.1
    environment:
      - STORAGE_PATH=/registry
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_HTTP_RELATIVEURLS=true
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - backend
      - proxy

  gui:
    image: joxit/docker-registry-ui:1.1-static
    networks:
      - backend
      - proxy

volumes:
  registry-data:

networks:
  backend:
  proxy:
    external:
      name: proxy_backend
```
