### ISSUE TITLE
  invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don't have permission to access /v2/sms.domain.com/blobs/uploads/\non this server.<br />\n</p>\n<hr>\n<address>Apache/2.4.10 (Debian) Server at docker.domain.com Port 80</address>\n</body></html>\n"

### ISSUE THREAD

**Issue by manjunathpm** [kwk/docker-registry-frontend#222]
## Expected behavior

- I have built my docker image on my local machine for one of my project and also hosted up an docker private repository to push and pull images

## Actual behavior

- when I tried to push the image to docker private repository I getting this error
```  invalid character '<' looking for beginning of value: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don't have permission to access /v2/sms.protridentechnologies.com/blobs/uploads/\non this server.<br />\n</p>\n<hr>\n<address>Apache/2.4.10 (Debian) Server at docker.visticloud.com Port 80</address>\n</body></html>\n"```

## Steps to reproduce the problem

- I have hosted this private docker repository on oracle cloud having arm processer. I have hosted docker Private repository using docker compose file below is my docker compose file details

```
version: '3'
services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./volume:/var/lib/registry

  docker-registry-ui:
    image: ryansmick/arm-docker-registry-frontend:1.0
    container_name: docker-registry-ui
    ports:
      - 8080:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: docker-registry
      ENV_DOCKER_REGISTRY_PORT: 5000
     
```

## Specifications

 - [x] Which version of docker (`docker version`) are you running?
 Ans: Docker version 23.0.4, build f480fb1 on cloud
 Docker version 19.03.1, build 74b1e89e8a on local machine
 
 - [x] Which operating system do you use?
 ans: on cloud it's `Canonical Ubuntu 22.04 aarch64` on my local machine it's `windows 10`
 
 - [x] Which version of the docker-registry-frontend are you running?
  * ryansmick/arm-docker-registry-frontend:1.0
  * Otherwise you can provide the output of `docker images | grep "docker-registry-frontend"`.
  Ans: `ryansmick/arm-docker-registry-frontend   1.0       014a07ca3340   5 years ago   244MB`
