### ISSUE TITLE
Environment Vars don't seem to apply, as docker frontend is XHR calls to it's own url

### ISSUE THREAD

**Issue by Spittal** [kwk/docker-registry-frontend#80]
Hey I'm having some troubles setting this up on an AWS EC2 instance running ubuntu. To make things easy on myself I've set up both the registry and the frontend on the same EC2 instance and I use docker-compose to configure them.

Here is my docker compose file.

```
registry:
  image: registry:2
  ports:
    - "5000:5000"
  volumes:
    - /home/ubuntu/registry-config.yml:/etc/docker/registry/config.yml
    - /home/ubuntu/certs:/certs
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
    REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
registry_frontend:
  image: konradkleine/docker-registry-frontend:v2
  ports:
    - "443:443"
  environment:
    ENV_DOCKER_REGISTRY_HOST: localhost
    ENV_DOCKER_REGISTRY_PORT: 5000
    ENV_REGISTRY_PROXY_FQDN: my-cool-docker-registry.com
    ENV_REGISTRY_PROXY_PORT: 80
    ENV_USE_SSL: 'yes'
  volumes:
    - /home/ubuntu/certs/fullchain.pem:/etc/apache2/server.crt:ro
    - /home/ubuntu/certs/privkey.pem:/etc/apache2/server.key:ro
```

And here is my configuration for my registry. You can see it's listening for requests on port 5000.

```
version: 0.1
log:
  fields:
    service: registry
storage:
    s3:
        accesskey: key
        secretkey: secret
        region: us-east-1
        bucket:docker-registry
        encrypt: false
        secure: true
        v4auth: true
        chunksize: 5242880
    cache:
        blobdescriptor: inmemory
http:
    addr: :5000
    headers:
        X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

Now I can get all this to run, and accessing the domain with https does work. However, When the frontend makes a call to get information about the images it comes back with a 502 error because it's trying to call on the same domain and port as the frontend.

I'm certain there's something wrong with my config but I can't seem to figure out what.

**Comment by Spittal** [comment]
I followed the example-config that was outlined in the repo and I was able (with a bit of tweaking to get it to work) for those who need this for reference

I am using letsencrypt to generate my certs (again just for reference)

new docker-compose.yml

```
registry:
  image: registry:2.2.0
  volumes:
    - ./registry-config.yml:/etc/docker/registry/config.yml
    - ./registry-data:/var/lib/registry:rw
    - ./certs:/certs:ro
  ports:
      - "0.0.0.0:5000:5000"
frontend:
  image: konradkleine/docker-registry-frontend:v2
  links:
    - registry:registry
  ports:
    - "0.0.0.0:8443:443"
  volumes:
    - ./certs/fullchain.pem:/etc/apache2/server.crt:ro
    - ./certs/privkey.pem:/etc/apache2/server.key:ro
  environment:
    - ENV_USE_SSL=yes
    - ENV_DOCKER_REGISTRY_HOST=registry
    - ENV_DOCKER_REGISTRY_PORT=5000
    - ENV_DOCKER_REGISTRY_USE_SSL=1
```

new registry-config.yml

```
version: 0.1
log:
  level: info
  formatter: text
  fields:
    service: registry
    environment: production
storage:
    s3:
        accesskey: [somekey]
        secretkey: [somekey]
        region: us-east-1
        bucket: docker-time!
        encrypt: false
        secure: true
        v4auth: true
        chunksize: 5242880
    cache:
        blobdescriptor: inmemory
http:
    addr: :5000
    tls:
        certificate: /certs/fullchain.pem
        key: /certs/privkey.pem
    headers:
        X-Content-Type-Options: [nosniff]
    debug:
        addr: :5001
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
