### ISSUE TITLE
HTTP: attempt to connect to 127.0.0.1:5000 (localhost) failed

### ISSUE THREAD

**Issue by Haitianisgood** [kwk/docker-registry-frontend#81]
Thanks for this contribution!!!

I access some errors.

my docker registry 2：

```
docker run --rm -p 5000:5000  --name registry \
  -v `pwd`/data:/var/lib/registry \
  registry:2
```

my docker-registry-frontend's  docker-compose.yml:

```
frontend:
  image: konradkleine/docker-registry-frontend:v2

  environment:
    ENV_DOCKER_REGISTRY_HOST: localhost
    ENV_DOCKER_REGISTRY_PORT: 5000
    ENV_USE_SSL: "yes"
    ENV_MODE_BROWSE_ONLY: "True"
  volumes:
    - ./certs/server.crt:/etc/apache2/server.crt:ro
    - ./certs/server.key:/etc/apache2/server.key:ro
  ports:
    - "443:443"

```

when I run ：

```
root@bz:~docker push www.haitian.com/hello-world
The push refers to a repository [www.haitian.com/hello-world] (len: 1)
Sending image list
Error: Status 403 trying to push repository hello-world: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>403 Forbidden</title>\n</head><body>\n<h1>Forbidden</h1>\n<p>You don't have permission to access /v1/repositories/hello-world/\non this server.<br />\n</p>\n<hr>\n<address>Apache/2.4.10 (Debian) Server at www.haitian.com Port 443</address>\n</body></html>\n"

```

and my  konradkleine/docker-registry-frontend report:

```

frontend_1 | [Tue Dec 29 07:27:08.748051 2015] [proxy:error] [pid 50:tid 140659960829696] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:5000 (localhost) failed
frontend_1 | [Tue Dec 29 07:27:08.748102 2015] [proxy:error] [pid 50:tid 140659960829696] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
frontend_1 | [Tue Dec 29 07:27:08.748114 2015] [proxy_http:error] [pid 50:tid 140659960829696] [client 192.168.1.13:36039] AH01114: HTTP: failed to make connection to backend: localhost
frontend_1 | 192.168.1.13 - - [29/Dec/2015:07:27:08 +0000] "GET /v2/ HTTP/1.1" 503 2935 "-" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.13.0-32-generic os/linux arch/amd64"
frontend_1 | [Tue Dec 29 07:27:08.774295 2015] [proxy:error] [pid 49:tid 140660077340416] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:5000 (localhost) failed
frontend_1 | [Tue Dec 29 07:27:08.774323 2015] [proxy:error] [pid 49:tid 140660077340416] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
frontend_1 | [Tue Dec 29 07:27:08.774331 2015] [proxy_http:error] [pid 49:tid 140660077340416] [client 192.168.1.13:36042] AH01114: HTTP: failed to make connection to backend: localhost
frontend_1 | 192.168.1.13 - - [29/Dec/2015:07:27:08 +0000] "GET /v2/ HTTP/1.1" 503 2935 "-" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.13.0-32-generic os/linux arch/amd64"
frontend_1 | 192.168.1.13 - - [29/Dec/2015:07:27:08 +0000] "GET /v1/_ping HTTP/1.1" 200 3490 "-" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.13.0-32-generic os/linux arch/amd64"
frontend_1 | [Tue Dec 29 07:27:08.815096 2015] [access_compat:error] [pid 50:tid 140659952436992] [client 192.168.1.13:36046] AH01797: client denied by server configuration: /var/www/html/v1
frontend_1 | 192.168.1.13 - - [29/Dec/2015:07:27:08 +0000] "PUT /v1/repositories/hello-world/ HTTP/1.1" 403 2844 "-" "docker/1.9.1 go/go1.4.2 git-commit/a34a1d5 kernel/3.13.0-32-generic os/linux arch/amd64"

```

Thanks !!!
