### ISSUE TITLE
latest vs v2 problem

### ISSUE THREAD

**Issue by farahfa** [kwk/docker-registry-frontend#92]
Hello,

I've pulled both images "latest" and "v2" from docker hub today and when I run the "latest" image, no repositories show up on the page, however when I run "v2" the repositories show up. 

Here's how I'm running them.

latest:

`docker run --detach --env=ENV_DOCKER_REGISTRY_HOST=172.17.0.1 --env=ENV_DOCKER_REGISTRY_PORT=5000 --publish=80:80 --name=kwk-frontend-ui --restart always konradkleine/docker-registry-frontend:latest`

v2:

`docker run --detach --env=ENV_DOCKER_REGISTRY_HOST=172.17.0.1 --env=ENV_DOCKER_REGISTRY_PORT=5000 --publish=80:80 --name=kwk-frontend-ui-2 --restart always konradkleine/docker-registry-frontend:v2`

And here's how the pages look like:

latest:

![screen shot 2016-02-01 at 9 35 18 am](https://cloud.githubusercontent.com/assets/9218600/12720132/1fcdd3ea-c8c7-11e5-8fde-4ce9468a5149.png)

v2:

![screen shot 2016-02-01 at 9 34 02 am](https://cloud.githubusercontent.com/assets/9218600/12720127/1a4a31d4-c8c7-11e5-9ee9-d75da6866f20.png)

Another thing, in v2 sometimes when I click on "Browse Repositories" on the main page it goes to "http://localhost/repositories/20" (searches for 20; which shows nothing obviously).

Thanks,

Fadi

**Comment by kwk** [comment]
@farahfa  Please see example setup folder in github project for a working setup.

**Comment by RemyCH** [comment]
Hi guys,

 I have the exact same pb. v2 installed and we see repos but can't suppress anything even with `BROWSE_ONLY=false` in our docker-compose.
We try the "lastest" version and we see Nothing in the repo.

 I have check your "example setup", but it's seem do be a merge of v1/v2 setup? As an example your docker config.yml is for a v1 ? The docker-compose for a v2. Some configuration seems directly linked to the v1 version of the registry?
 Nothing for a "latest" version.

 Our configuration is really simple, no SSL at all. We just configure it to expose 8081:80 on the frontend, linked it to our registry:5000 and that's all :/
 On the same host. 

 Our docker-compose :

``` yaml
docker-registry:                                                                                                                       
  image: registry:2.1.1                                                                                                             
  ports:                                                                                                                                 
    - "127.0.0.1:5000:5000"                                                                                                              
  volumes:                                                                                                                           
    - /forge/registry/data:/var/lib/registry                                                                     
    - /etc/localtime:/etc/localtime:ro
  container_name: docker-registry

docker-registry-frontend:
#  image: docker.io/konradkleine/docker-registry-frontend:latest
  image: docker.io/konradkleine/docker-registry-frontend:v2
  ports:
    - "8081:80"
  environment:
    - ENV_DOCKER_REGISTRY_HOST=docker-registry
    - ENV_DOCKER_REGISTRY_PORT=5000
    - ENV_MODE_BROWSE_ONLY=false
  container_name: docker-registry-frontend
  hostname: frontend
  links:
    - docker-registry:docker-registry
```

/etc/sysconfig/docker cut :

```
# If you have a registry secured with https but do not have proper certs
# distributed, you can tell docker to not look for full authorization by
# adding the registry to the INSECURE_REGISTRY line and uncommenting it.
INSECURE_REGISTRY='--insecure-registry dr.forge-siterc'
```

 Sorry for my English if it's not clear enough..

tx
Regards
RCH
